// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrwyeutvebxcezyatkbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhyd3lldXR2ZWJ4Y2V6eWF0a2JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDc4NDksImV4cCI6MjA2ODIyMzg0OX0.R3HNqhplhavvmPxBDxiisWyk76Y87RxAIHkDxSXa5mc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});